import type { HomeContent } from "@/lib/api/types";
import { delay } from "@/lib/api-mock/delay";
import { stockTravelImage } from "@/lib/api-mock/stock-image";

const cardImg = (seed: number) => stockTravelImage(seed, 640, 720);

/** Local assets for «Минимальные цены по направлениям» (user-provided photos) */
const MIN_PRICE_IMG = {
  beach: "/destinations/min-price-turkey.png",
  resort: "/destinations/min-price-resort.png",
  pool: "/destinations/min-price-pool.png",
} as const;

/** Local assets for «Спецпредложения» section */
const SPECIAL_OFFER_IMG = {
  so1: "/images/special-offers/special-offer-1.png",
  so2: "/images/special-offers/special-offer-2.png",
  so3: "/images/special-offers/special-offer-3.png",
} as const;

export async function getHomeContentMock(): Promise<HomeContent> {
  await delay(380);
  return {
    directionPrices: [
      {
        id: "dp1",
        name: "Турция",
        priceFrom: 35000,
        imageUrl: MIN_PRICE_IMG.beach,
      },
      {
        id: "dp2",
        name: "Таиланд",
        priceFrom: 80000,
        imageUrl: MIN_PRICE_IMG.resort,
      },
      {
        id: "dp3",
        name: "ОАЭ",
        priceFrom: 70000,
        imageUrl: MIN_PRICE_IMG.pool,
      },
      {
        id: "dp4",
        name: "Египет",
        priceFrom: 42000,
        imageUrl: MIN_PRICE_IMG.resort,
      },
      {
        id: "dp5",
        name: "Греция",
        priceFrom: 65000,
        imageUrl: MIN_PRICE_IMG.beach,
      },
      {
        id: "dp6",
        name: "Мальдивы",
        priceFrom: 195000,
        imageUrl: MIN_PRICE_IMG.pool,
      },
      {
        id: "dp7",
        name: "Кипр",
        priceFrom: 58000,
        imageUrl: MIN_PRICE_IMG.beach,
      },
      {
        id: "dp8",
        name: "Испания",
        priceFrom: 72000,
        imageUrl: MIN_PRICE_IMG.resort,
      },
    ],
    hotTours: [
      {
        id: "ht1",
        title: "Турция, Анталия",
        subtitle: "AI • 7 ночей • вылет из Москвы",
        priceFrom: 28900,
        nights: 7,
        imageUrl: cardImg(1),
        badge: "горящий",
        hotelName: "Grand Paradise Hotel",
        rating: 5,
        stars: 5,
        locationLabel: "Турция, Анталия",
        dateLabel: "20 дек • 7 ночей",
        mealType: "All Inclusive",
        charter: true,
        roomType: "Deluxe",
        guestsLabel: "2 взрослых",
      },
      {
        id: "ht2",
        title: "Египет, Хургада",
        subtitle: "5* • всё включено",
        priceFrom: 35200,
        nights: 7,
        imageUrl: cardImg(2),
        badge: "горящий",
        hotelName: "Coral Bay Suites",
        rating: 4.8,
        stars: 5,
        locationLabel: "Египет, Хургада",
        dateLabel: "18 дек • 7 ночей",
        mealType: "UAI",
        charter: false,
        roomType: "Family Suite",
        guestsLabel: "2 взрослых",
      },
      {
        id: "ht3",
        title: "ОАЭ, Дубай",
        subtitle: "Премиум отели",
        priceFrom: 61200,
        nights: 5,
        imageUrl: cardImg(3),
        hotelName: "Palm Horizon",
        rating: 4.9,
        stars: 5,
        locationLabel: "ОАЭ, Дубай",
        dateLabel: "5 янв • 5 ночей",
        mealType: "BB",
        charter: false,
        roomType: "Superior",
        guestsLabel: "2 взрослых",
      },
    ],
    hotelSpotlight: [
      {
        id: "hs1",
        title: "Grand Paradise Hotel",
        subtitle: "Анталия • первая линия",
        priceFrom: 32000,
        nights: 7,
        imageUrl: cardImg(4),
        hotelName: "Grand Paradise Hotel",
        rating: 5,
        stars: 5,
        locationLabel: "Турция, Анталия",
        dateLabel: "22 дек • 7 ночей",
        mealType: "All Inclusive",
        charter: true,
        roomType: "Deluxe Sea View",
        guestsLabel: "2 взрослых",
      },
      {
        id: "hs2",
        title: "Aegean Pearl Resort",
        subtitle: "Крит • семейный отдых",
        priceFrom: 59000,
        nights: 10,
        imageUrl: cardImg(5),
        hotelName: "Aegean Pearl Resort",
        rating: 4.7,
        stars: 4,
        locationLabel: "Греция, Крит",
        dateLabel: "14 янв • 10 ночей",
        mealType: "HB",
        charter: true,
        roomType: "Standard",
        guestsLabel: "2 взрослых, 1 ребёнок",
      },
      {
        id: "hs3",
        title: "Serenity Maldives Villa",
        subtitle: "Мальдивы • water villa",
        priceFrom: 238000,
        nights: 7,
        imageUrl: cardImg(6),
        hotelName: "Serenity Maldives Villa",
        rating: 5,
        stars: 5,
        locationLabel: "Мальдивы, Мале",
        dateLabel: "8 фев • 7 ночей",
        mealType: "AI",
        charter: false,
        roomType: "Water Villa",
        guestsLabel: "2 взрослых",
      },
      {
        id: "hs4",
        title: "Azure Bay Hotel",
        subtitle: "Испания, Коста-Брава",
        priceFrom: 44500,
        nights: 7,
        imageUrl: cardImg(7),
        hotelName: "Azure Bay Hotel",
        rating: 4.6,
        stars: 4,
        locationLabel: "Испания, Льорет-де-Мар",
        dateLabel: "3 мар • 7 ночей",
        mealType: "HB",
        charter: true,
        roomType: "Standard",
        guestsLabel: "2 взрослых",
      },
      {
        id: "hs5",
        title: "Lagoon Phuket Resort",
        subtitle: "Таиланд • пляж Карон",
        priceFrom: 88400,
        nights: 10,
        imageUrl: cardImg(8),
        hotelName: "Lagoon Phuket Resort",
        rating: 4.8,
        stars: 5,
        locationLabel: "Таиланд, Пхукет",
        dateLabel: "12 фев • 10 ночей",
        mealType: "AI",
        charter: false,
        roomType: "Deluxe Pool",
        guestsLabel: "2 взрослых",
      },
      {
        id: "hs6",
        title: "Nile View Palace",
        subtitle: "Египет • Луксор",
        priceFrom: 49800,
        nights: 7,
        imageUrl: cardImg(9),
        hotelName: "Nile View Palace",
        rating: 4.5,
        stars: 5,
        locationLabel: "Египет, Луксор",
        dateLabel: "25 янв • 7 ночей",
        mealType: "BB",
        charter: true,
        roomType: "Nile View",
        guestsLabel: "2 взрослых",
      },
    ],
    specialOffers: [
      {
        id: "so1",
        title: "Раннее бронирование",
        description:
          "Забронируйте тур за 3 месяца и получите скидку до 30%",
        discountLabel: "-30%",
        scopeLabel: "Все направления",
        imageUrl: SPECIAL_OFFER_IMG.so1,
      },
      {
        id: "so2",
        title: "Семейный отдых",
        description:
          "Дети до 12 лет — спецусловия и скидки на размещение в отелях-партнёрах",
        discountLabel: "детям бесплатно",
        scopeLabel: "Турция, Египет",
        imageUrl: SPECIAL_OFFER_IMG.so2,
      },
      {
        id: "so3",
        title: "Премиум направления",
        description: "Мальдивы, ОАЭ, Таиланд — фиксированные цены на ранний вылет",
        discountLabel: "-20%",
        scopeLabel: "Азия и ОАЭ",
        imageUrl: SPECIAL_OFFER_IMG.so3,
      },
      {
        id: "so4",
        title: "Новогодние каникулы",
        description:
          "Фиксированные цены на Турцию и Египет при бронировании до 15 декабря",
        discountLabel: "-15%",
        scopeLabel: "Турция, Египет",
        imageUrl: SPECIAL_OFFER_IMG.so1,
      },
      {
        id: "so5",
        title: "Медовый месяц",
        description:
          "Подарочный сертификат на ужин и трансфер для пар при бронировании от 7 ночей",
        discountLabel: "подарок",
        scopeLabel: "Мальдивы, Сейшелы",
        imageUrl: SPECIAL_OFFER_IMG.so2,
      },
      {
        id: "so6",
        title: "Горнолыжные туры",
        description: "Раннее бронирование на Альпы и Кавказ — лучшие отели у подъёмников",
        discountLabel: "-10%",
        scopeLabel: "Европа, Россия",
        imageUrl: SPECIAL_OFFER_IMG.so3,
      },
    ],
    advantages: [
      {
        id: "a1",
        icon: "headset",
        title: "Поддержка 24/7",
        description: "Всегда на связи в любое время",
      },
      {
        id: "a2",
        icon: "creditCard",
        title: "Онлайн оплата",
        description: "Безопасные платежи через ЮKassa",
      },
      {
        id: "a3",
        icon: "thumbsUp",
        title: "Лучшие цены",
        description: "Гарантия низкой цены на туры",
      },
      {
        id: "a4",
        icon: "handHeart",
        title: "Надежность",
        description: "15 лет на рынке туризма",
      },
      {
        id: "a5",
        icon: "users",
        title: "Опытные менеджеры",
        description: "Профессиональная консультация",
      },
      {
        id: "a6",
        icon: "globe",
        title: "50+ направлений",
        description: "Туры по всему миру на любой вкус",
      },
      {
        id: "a7",
        icon: "medal",
        title: "Награды и признание",
        description: "Лучшее турагентство 2023 года",
      },
      {
        id: "a8",
        icon: "trendUp",
        title: "50 000+ туристов",
        description: "Довольных клиентов за 15 лет",
      },
    ],
    reviews: [
      {
        id: "r1",
        author: "Анна Петрова",
        text: "Прекрасный отдых! Все было организовано на высшем уровне. Отель соответствовал описанию, трансфер вовремя. Менеджер помог подобрать идеальный вариант под наш бюджет. Обязательно обратимся снова!",
        rating: 5,
        locationLabel: "Турция, Анталия",
        date: "Октябрь 2024",
      },
      {
        id: "r2",
        author: "Алексей П.",
        text: "Удобный поиск и понятные фильтры. Нашли отличный вариант в Турцию.",
        rating: 5,
        locationLabel: "Турция, Алания",
        date: "Февраль 2026",
      },
      {
        id: "r3",
        author: "Елена С.",
        text: "Менеджер помог с документами и ответил на все вопросы очень быстро.",
        rating: 4,
        locationLabel: "Египет, Хургада",
        date: "Январь 2026",
      },
      {
        id: "r4",
        author: "Мария К.",
        text: "Второй раз бронируем через Асторию. Цены честные, никаких скрытых доплат. Рекомендую!",
        rating: 5,
        locationLabel: "ОАЭ, Дубай",
        date: "Декабрь 2025",
      },
      {
        id: "r5",
        author: "Дмитрий В.",
        text: "Очень удобно сравнивать отели и даты в одном месте. Оформили тур за вечер.",
        rating: 5,
        locationLabel: "Греция, Родос",
        date: "Ноябрь 2025",
      },
      {
        id: "r6",
        author: "Ольга Н.",
        text: "Хорошая страховка и напоминания перед вылетом — мелочь, а приятно.",
        rating: 4,
        locationLabel: "Таиланд, Паттайя",
        date: "Сентябрь 2025",
      },
      {
        id: "r7",
        author: "Игорь Т.",
        text: "Сложный маршрут с пересадками собрали без проблем. Спасибо менеджеру Анне.",
        rating: 5,
        locationLabel: "Испания, Барселона",
        date: "Август 2025",
      },
    ],
  };
}
