import type { Hotel } from "@/lib/api/types";
import { stockTravelImage } from "@/lib/api-mock/stock-image";

const img = (seed: number) => stockTravelImage(seed + 100, 800, 520);

export const MOCK_HOTELS: Hotel[] = [
  {
    id: "h1",
    name: "Grand Paradise Hotel",
    stars: 5,
    rating: 5.0,
    country: "Турция",
    resort: "Анталия",
    locationLabel: "Турция, Анталия, Белек",
    mealType: "AI / UAI",
    priceFrom: 284186,
    imageUrl: img(11),
    firstLine: true,
    description:
      "Роскошный отель расположен на берегу Средиземного моря в престижном районе Белек. Отель предлагает высококлассный сервис, разнообразное питание и множество развлечений для гостей всех возрастов.",
  },
  {
    id: "h2",
    name: "Aegean Pearl Resort",
    stars: 4,
    rating: 4.6,
    country: "Греция",
    resort: "Крит",
    locationLabel: "Греция, Крит",
    mealType: "HB / FB",
    priceFrom: 59000,
    imageUrl: img(12),
    firstLine: false,
    description:
      "Уютный курорт у моря с бассейнами, спа и ресторанами. Подходит для спокойного семейного отдыха.",
  },
  {
    id: "h3",
    name: "Coral Bay Suites",
    stars: 4,
    rating: 4.2,
    country: "Египет",
    resort: "Хургада",
    locationLabel: "Египет, Хургада",
    mealType: "UAI",
    priceFrom: 45000,
    imageUrl: img(13),
    firstLine: true,
  },
  {
    id: "h4",
    name: "Palm Horizon",
    stars: 5,
    rating: 4.8,
    country: "ОАЭ",
    resort: "Дубай",
    locationLabel: "ОАЭ, Дубай",
    mealType: "BB / HB",
    priceFrom: 87000,
    imageUrl: img(14),
    firstLine: false,
  },
  {
    id: "h5",
    name: "Laguna Beach Hotel",
    stars: 3,
    rating: 3.9,
    country: "Турция",
    resort: "Алания",
    locationLabel: "Турция, Алания",
    mealType: "AI",
    priceFrom: 26000,
    imageUrl: img(15),
    firstLine: true,
  },
  {
    id: "h6",
    name: "Serenity Maldives Villa",
    stars: 5,
    rating: 4.9,
    country: "Мальдивы",
    resort: "Мале",
    locationLabel: "Мальдивы, Мале",
    mealType: "AI",
    priceFrom: 238000,
    imageUrl: img(16),
    firstLine: true,
  },
];
