import type { Tour } from "@/lib/api/types";
import { stockTravelImage } from "@/lib/api-mock/stock-image";

const img = (seed: number) => stockTravelImage(seed + 40, 800, 520);

/** Distinct mock photos per tour for hover gallery. */
function galleryFor(seed: number): string[] {
  return [
    img(seed),
    img(seed + 31),
    img(seed + 62),
    img(seed + 93),
  ];
}

export const MOCK_TOURS: Tour[] = [
  {
    id: "t1",
    hotelName: "Grand Paradise Hotel",
    rating: 5.0,
    stars: 5,
    country: "Турция",
    resort: "Анталия",
    locationLabel: "Турция, Анталия",
    dateLabel: "20 дек • 7 ночей",
    nights: 7,
    mealType: "All Inclusive",
    isHot: false,
    charter: true,
    roomType: "Deluxe",
    guestsLabel: "2 взрослых",
    priceFrom: 35000,
    imageUrl: img(1),
    galleryImageUrls: galleryFor(1),
    imageBadgeLabel: "Хит продаж",
    distanceLabel: "500 м до моря",
    featureTags: [
      { label: "Отдых с детьми", tone: "green" },
      { label: "Комфорт класс", tone: "teal" },
      { label: "Новый отель", tone: "blue" },
      { label: "VIP", tone: "gold" },
    ],
    amenities: ["balcony", "wifi", "airCon", "kitchen"],
  },
  {
    id: "t2",
    hotelName: "Aegean Pearl Resort",
    rating: 4.6,
    stars: 4,
    country: "Греция",
    resort: "Крит",
    locationLabel: "Греция, Крит",
    dateLabel: "15 янв • 10 ночей",
    nights: 10,
    mealType: "HB",
    isHot: false,
    charter: true,
    roomType: "Standard",
    guestsLabel: "2 взрослых",
    priceFrom: 62000,
    imageUrl: img(2),
    galleryImageUrls: galleryFor(2),
    distanceLabel: "800 м до пляжа",
    featureTags: [{ label: "Раннее бронирование", tone: "blue" }],
    amenities: ["balcony", "wifi", "airCon"],
  },
  {
    id: "t3",
    hotelName: "Coral Bay Suites",
    rating: 4.2,
    stars: 4,
    country: "Египет",
    resort: "Хургада",
    locationLabel: "Египет, Хургада",
    dateLabel: "8 фев • 7 ночей",
    nights: 7,
    mealType: "UAI",
    isHot: true,
    charter: false,
    roomType: "Family",
    guestsLabel: "2 взрослых, 1 ребёнок",
    priceFrom: 48000,
    imageUrl: img(3),
    galleryImageUrls: galleryFor(3),
    distanceLabel: "Первая линия, 50 м до моря",
    featureTags: [
      { label: "Отдых с детьми", tone: "green" },
      { label: "Анимация", tone: "teal" },
    ],
    amenities: ["wifi", "airCon", "kitchen"],
  },
  {
    id: "t4",
    hotelName: "Palm Horizon",
    rating: 4.8,
    stars: 5,
    country: "ОАЭ",
    resort: "Дубай",
    locationLabel: "ОАЭ, Дубай",
    dateLabel: "3 мар • 5 ночей",
    nights: 5,
    mealType: "BB",
    isHot: false,
    charter: false,
    roomType: "Superior",
    guestsLabel: "2 взрослых",
    priceFrom: 89500,
    imageUrl: img(4),
    galleryImageUrls: galleryFor(4),
  },
  {
    id: "t5",
    hotelName: "Laguna Beach Hotel",
    rating: 3.9,
    stars: 3,
    country: "Турция",
    resort: "Алания",
    locationLabel: "Турция, Алания",
    dateLabel: "12 апр • 12 ночей",
    nights: 12,
    mealType: "AI",
    isHot: false,
    charter: true,
    roomType: "Standard",
    guestsLabel: "2 взрослых",
    priceFrom: 28900,
    imageUrl: img(5),
    galleryImageUrls: galleryFor(5),
  },
  {
    id: "t6",
    hotelName: "Serenity Maldives Villa",
    rating: 4.9,
    stars: 5,
    country: "Мальдивы",
    resort: "Мале",
    locationLabel: "Мальдивы, Мале",
    dateLabel: "22 мая • 7 ночей",
    nights: 7,
    mealType: "AI",
    isHot: true,
    charter: false,
    roomType: "Water Villa",
    guestsLabel: "2 взрослых",
    priceFrom: 245000,
    imageUrl: img(6),
    galleryImageUrls: galleryFor(6),
  },
  {
    id: "t7",
    hotelName: "Blue Marina",
    rating: 4.4,
    stars: 4,
    country: "Турция",
    resort: "Бодрум",
    locationLabel: "Турция, Бодрум",
    dateLabel: "1 июн • 7 ночей",
    nights: 7,
    mealType: "FB",
    isHot: false,
    charter: true,
    roomType: "Deluxe Sea View",
    guestsLabel: "2 взрослых",
    priceFrom: 51200,
    imageUrl: img(7),
    galleryImageUrls: galleryFor(7),
  },
  {
    id: "t8",
    hotelName: "Sunrise Kemer",
    rating: 4.1,
    stars: 4,
    country: "Турция",
    resort: "Кемер",
    locationLabel: "Турция, Кемер",
    dateLabel: "18 июл • 9 ночей",
    nights: 9,
    mealType: "AI",
    isHot: true,
    charter: true,
    roomType: "Standard",
    guestsLabel: "2 взрослых",
    priceFrom: 41000,
    imageUrl: img(8),
    galleryImageUrls: galleryFor(8),
  },
  {
    id: "t9",
    hotelName: "Alpine Lodge",
    rating: 4.7,
    stars: 4,
    country: "Италия",
    resort: "Доломиты",
    locationLabel: "Италия, Доломиты",
    dateLabel: "10 янв • 6 ночей",
    nights: 6,
    mealType: "HB",
    isHot: false,
    charter: false,
    roomType: "Chalet",
    guestsLabel: "2 взрослых",
    priceFrom: 78000,
    imageUrl: img(9),
    galleryImageUrls: galleryFor(9),
  },
  {
    id: "t10",
    hotelName: "City Lights Bangkok",
    rating: 4.3,
    stars: 4,
    country: "Таиланд",
    resort: "Бангкок",
    locationLabel: "Таиланд, Бангкок",
    dateLabel: "5 ноя • 4 ночи",
    nights: 4,
    mealType: "BB",
    isHot: false,
    charter: false,
    roomType: "City",
    guestsLabel: "2 взрослых",
    priceFrom: 55000,
    imageUrl: img(10),
    galleryImageUrls: galleryFor(10),
  },
];
